# Generated by Django 4.0 on 2022-02-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent_Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Numbers',
            new_name='Received_Numbers',
        ),
        migrations.AddField(
            model_name='tasks',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
