# Generated by Django 4.0 on 2022-02-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('dashboard', '0003_sent_numbers_rename_numbers_received_numbers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_number', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('received_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.received_numbers')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dashboard.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.profile')),
            ],
        ),
    ]
