# Generated by Django 4.0 on 2022-03-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('offers', '__first__'),
        ('dashboard', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_received_numbers', models.IntegerField()),
                ('monthly_offers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.monthly_offers')),
                ('normal_offers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.normal_offers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.profile')),
            ],
        ),
    ]
