# Generated by Django 4.0 on 2022-03-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_user_config_total_received_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
