# Generated by Django 4.0 on 2022-03-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_tasks_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='ranges',
            field=models.IntegerField(),
        ),
    ]
