# Generated by Django 4.0 on 2022-03-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_tasks_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_send',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='date_work',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_config',
            name='sent_number_type',
            field=models.CharField(default='shared', max_length=20),
        ),
    ]
