# Generated by Django 4.0 on 2022-03-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_message_date_send_tasks_date_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_config',
            name='daily_operations',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user_config',
            name='day_use',
            field=models.IntegerField(default=0),
        ),
    ]
